version: '3.0'
services:
  container-live:
    container_name: image-graalvm-community-17
    image: image-graalvm-community-17
    deploy:
      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 2048M
    tty: true
  container-live-jdk21:
    container_name: graalvm-sdk21
    image: image-graalvm-21
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 512M
        reservations:
          cpus: '0.0001'
          memory: 20M
    tty: true
  app-TestBuildNativeImage:
    image: "image-graalvm-17"
    entrypoint: ["java","-cp","app.jar", "br.com.fabex.TestBuildNativeImage"]